channels:
- conda-forge
- bioconda
dependencies:
- bioconda::foldseek=10.941cd33
- bioconda::mmseqs2=18.8cc5c
- bioconda::seqkit=2.11.0
- conda-forge::csvtk=0.36.0
- conda-forge::pigz=2.8
- conda-forge::zstd=1.5.7
